# Generated by Django 5.2.12 on 2026-03-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("content",),
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
    ]
